# Generated by Django 4.1.3 on 2022-12-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='table2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('det', models.TextField()),
            ],
        ),
    ]
