# Generated by Django 4.1.4 on 2022-12-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_remove_task_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
    ]
